version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: bdautogestion
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"

  django:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=bdautogestion
      - DB_USER=root
      - DB_PASS=123456
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TIMEZONE=America/Bogota

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=bdautogestion
      - DB_USER=root
      - DB_PASS=123456
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TIMEZONE=America/Bogota

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=bdautogestion
      - DB_USER=root
      - DB_PASS=123456
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TIMEZONE=America/Bogota

volumes:
  db_data:
