# Generated by Django 5.2.6 on 2025-09-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_user_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
