# Generated by Django 5.2.6 on 2025-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_user_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=True, help_text='True si el usuario está registrado pero no activado. False si ya fue activado.'),
        ),
    ]
