# Generated by Django 5.2.6 on 2025-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_user_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
