<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-23 20:55
=======
# Generated by Django 5.2.6 on 2025-09-21 17:43
>>>>>>> 90e102ff5d6798ffefd1e0151d8fb59f8a787a75

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codeCenter', models.BigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractType', models.CharField(max_length=50)),
                ('contractStartDate', models.DateField()),
                ('contractEndDate', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeleteAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Person Sede',
                'verbose_name_plural': 'Person Sedes',
                'db_table': 'general_personsede',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProgram', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('typeProgram', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codeRegional', models.BigIntegerField()),
                ('description', models.TextField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codeSede', models.BigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phoneSede', models.CharField(max_length=20)),
                ('emailContact', models.EmailField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
