# Generated by Django 4.2.23 on 2025-10-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsede',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.person'),
        ),
        migrations.AddField(
            model_name='personsede',
            name='SedeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.sede'),
        ),
        migrations.AddField(
            model_name='legalsection',
            name='documentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='general.legaldocument'),
        ),
        migrations.AddField(
            model_name='legalsection',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='general.legalsection'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='contractType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='general.typecontract'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='knowledgeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='general.knowledgearea'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='security.person'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='general.program'),
        ),
        migrations.AddField(
            model_name='center',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='general.regional'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprendices', to='general.ficha'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendices', to='security.person'),
        ),
    ]
