# Generated by Django 5.2.6 on 2025-09-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendices', to='security.person'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprendices', to='general.ficha'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='security.person'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='knowledgeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='general.knowledgearea'),
        ),
        migrations.AddField(
            model_name='personsede',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.person'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='general.program'),
        ),
        migrations.AddField(
            model_name='center',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='general.regional'),
        ),
        migrations.AddField(
            model_name='sede',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='general.center'),
        ),
        migrations.AddField(
            model_name='personsede',
            name='SedeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.sede'),
        ),
    ]
