# Generated by Django 5.2.6 on 2025-09-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='numeroFicha',
            new_name='file_number',
        ),
    ]
