# Generated by Django 5.2.6 on 2025-09-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='codeCenter',
            field=models.BigIntegerField(),
        ),
    ]
