# Generated by Django 5.2.6 on 2025-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_center_codecenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='file_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='codeProgram',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='regional',
            name='codeRegional',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sede',
            name='codeSede',
            field=models.BigIntegerField(),
        ),
    ]
