# Generated by Django 5.2.6 on 2025-09-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignationInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_asignation', models.DateField()),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_boss', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_boss', models.EmailField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_enterprise', models.CharField(max_length=100)),
                ('locate', models.CharField(max_length=255)),
                ('nit_enterprise', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('email_enterprise', models.EmailField(max_length=100)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumanTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalityProductiveStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_modality', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAsignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('date_start_production_stage', models.DateField()),
                ('pdf_request', models.FileField(blank=True, null=True, upload_to='requests/')),
                ('request_state', models.CharField(max_length=50)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('state_visit', models.CharField(max_length=50)),
                ('scheduled_date', models.DateField()),
                ('date_visit_made', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('name_visit', models.CharField(max_length=100)),
                ('observation_state_visit', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
