# Generated by Django 4.2.23 on 2025-10-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignationInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_asignation', models.DateField(auto_now_add=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignations', to='general.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_enterprise', models.CharField(max_length=100)),
                ('locate', models.CharField(max_length=255)),
                ('nit_enterprise', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('email_enterprise', models.EmailField(max_length=100)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalityProductiveStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_modality', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('state_visit', models.CharField(max_length=50)),
                ('scheduled_date', models.DateField()),
                ('date_visit_made', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('name_visit', models.CharField(max_length=100)),
                ('observation_state_visit', models.TextField(blank=True, null=True)),
                ('asignation_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='assign.asignationinstructor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAsignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('date_start_production_stage', models.DateField()),
                ('date_end_production_stage', models.DateField()),
                ('pdf_request', models.FileField(blank=True, null=True, upload_to='requests/')),
                ('request_state', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('SIN_ASIGNAR', 'Sin Asignar'), ('RECHAZADO', 'Rechazado')], default='SIN_ASIGNAR', max_length=50)),
                ('rejectionMessage', models.TextField(blank=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='general.aprendiz')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='assign.enterprise')),
                ('modality_productive_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='assign.modalityproductivestage')),
            ],
        ),
        migrations.CreateModel(
            name='HumanTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human_talent', to='assign.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_boss', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('email_boss', models.EmailField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='assign.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='AsignationInstructorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_instructor_id', models.IntegerField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('asignation_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assign.asignationinstructor')),
            ],
        ),
        migrations.AddField(
            model_name='asignationinstructor',
            name='request_asignation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignation_instructor', to='assign.requestasignation'),
        ),
    ]
