<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-29 01:29
=======
# Generated by Django 5.2.6 on 2025-09-28 06:16
>>>>>>> c1c925b4b7d8cdb7e9113fdc7cc496ed875c9ca9

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assign', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignationinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignations', to='general.instructor'),
        ),
        migrations.AddField(
            model_name='asignationinstructorhistory',
            name='asignation_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assign.asignationinstructor'),
        ),
        migrations.AddField(
            model_name='boss',
            name='enterprise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='assign.enterprise'),
        ),
        migrations.AddField(
            model_name='humantalent',
            name='enterprise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human_talent', to='assign.enterprise'),
        ),
        migrations.AddField(
            model_name='requestasignation',
            name='aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='general.aprendiz'),
        ),
        migrations.AddField(
            model_name='requestasignation',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='assign.enterprise'),
        ),
        migrations.AddField(
            model_name='requestasignation',
            name='modality_productive_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='assign.modalityproductivestage'),
        ),
        migrations.AddField(
            model_name='asignationinstructor',
            name='request_asignation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignation_instructor', to='assign.requestasignation'),
        ),
        migrations.AddField(
            model_name='visitfollowing',
            name='asignation_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='assign.asignationinstructor'),
        ),
    ]
