# Generated by Django 5.2.6 on 2025-09-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
