# Generated by Django 5.2.6 on 2025-09-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_boss_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='address',
        ),
    ]
