# Generated by Django 5.2.6 on 2025-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0004_remove_boss_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='nit_enterprise',
            field=models.BigIntegerField(),
        ),
    ]
