# Generated by Django 5.2.6 on 2025-09-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0005_alter_enterprise_nit_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='humantalent',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
